routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//users
Auth::routes();
Route::get('/account_overview', 'AccountController@showAccountOverview');

//home
Route::get('/', 'ProjectController@index')->name('home')->middleware('auth');
Route::get('/home', 'ProjectController@index')->name('home')->middleware('auth');

//child item
Route::get('/addchilditem', 'ChildItemController@showAddChildItemForm');
Route::post('/addchilditem', 'ChildItemController@saveItem')->name('saveItem');
Route::get('/edit_child_item/{id}', 'ChildItemController@showEditChildItemForm');
Route::post('/edit_child_item/{id}', 'ChildItemController@updateChildItem')->name('updateChildItem');
Route::get('/delete_child_item', 'ChildItemController@showDeleteChildItem');
Route::post('/delete_child_item/delete/{id}', 'ChildItemController@deleteChildItem')->name('deleteChildItem');
Route::get('/show_child_items', 'ChildItemController@showChildItems');

//Project
Route::resource('project', 'ProjectController')->middleware('auth');
Route::post('/project/{project}/add_teams','ProjectController@addTeams')->name('project.addTeam')->middleware('auth');
Route::delete('/project/{project}/delete_team/{team}','ProjectController@deleteTeam')->name('project.deleteTeam')->middleware('auth');

//Team
Route::resource('project.team', 'TeamController')->middleware('auth');
Route::delete('project/{project}/team/{team}/user/{user}', 'Teamcontroller@deleteUser')->name('team.deleteUser')->middleware('auth');
Route::put('project/{project}/team/{team}/updateRole/{user}', 'TeamController@updateRole')->name('team.updateRole')->middleware('auth');
Route::get('/teams', 'TeamController@getAllJoinedTeams')->name('teams')->middleware('auth');

//dod
Route::resource('project.dod', 'DoDController')->middleware('auth');
Route::post('project/{project}/dod/{definitionOfDone}/dod-item', 'DodController@createDodItem')->name('dod.dodItem.store')->middleware('auth');

//Sprint
Route::resource('project.sprint', 'SprintController')->middleware('auth');
Route::resource('sprints', 'SprintController')->middleware('auth');

//Item
Route::resource('project.sprint.item', 'ItemController')->middleware('auth');
Route::get('/items', 'ItemController@getAssignedItems')->name('items')->middleware('auth');

//Scrum
Route::resource('project.sprint.board', 'ScrumController')->only('index')->middleware('auth');

//Backlog
Route::resource('project.backlog', 'BacklogController')->only('index')->middleware('auth');

//ADMIN
Route::get('/admin_overview', 'AdminController@showAdminOverview');

//RetrospectiveItems
Route::resource('project.sprint.retrospectiveitem', 'RetrospectiveItemsController')->only('index')->middleware('auth');
Route::delete('retrospectiveitemsDestroy/{retrospective_items}', 'RetrospectiveItemsController@destroy')->name('destroyretrospectiveitem')->middleware('auth');
Route::post('retrospectiveitemStore/{sprint}', 'RetrospectiveItemsController@store')->name('storeretrospectiveitem')->middleware('auth');
Route::put('retrospectiveitemsUpdate/{retrospective_items}', 'RetrospectiveItemsController@update')->name('updateretrospectiveitem')->middleware('auth');

//SprintReview
Route::resource('project.sprint.sprintreview', 'SprintReviewController')->only('index')->middleware('auth');
Route::post('sprintreviewStore/{sprint}', 'SprintReviewController@store')->name('storesprintreview')->middleware('auth');
Route::delete('sprintreviewDestroy/{sprint_reviews}', 'SprintReviewController@destroy')->name('destroysprintreview')->middleware('auth');
Route::put('sprintreviewUpdate/{sprint_reviews}', 'SprintReviewController@update')->name('updatesprintreview')->middleware('auth');

resources/views/addChildItemForm.blade.php
@extends('layouts.app')

@section('content')
    <div class="row h-100">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <h1>child item toevoegen</h1>
            <form action={{route('saveItem')}} method="post">
                @csrf
                <div class="form-group">
                    <label>Naam:</label>
                    <input name="name" type="text" class="form-control" id="name">
                </div>

                <div class="form-group">
                    <label>Beschijving:</label>
                    <textarea name="description" type="text" class="form-control" id="description" rows="5" ></textarea>
                </div>

                <div class="form-group">
                    <label>Parent Item:</label>
                    <select class="form-control" id="parent_item" name="parent_item">
                        @foreach($parentItems as $parentItem)
                            <option value={{$parentItem->id}}>{{$parentItem->title}} </option>
                        @endforeach

                    </select>
                </div>

                <div class="form-group">
                    <label>asingnee:</label>
                    <select class="form-control" id="user" name="user">
                        @foreach($users as $user)
                            <option value={{$user->id}}>{{$user->username}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label>Type item:</label>
                    <select class="form-control" id="type" name="type">
                        @foreach($types as $type)
                            <option value={{$type->id}}>{{$type->type}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label>Punten:</label>
                    <input name="story_points" type="number" class="form-control" id="story_points">
                </div>

                <div class="form-group">
                    <label>Business value:</label>
                    <input name="business_value" type="number" class="form-control" id="business_value">
                </div>

                <div class="btn-group">
                    <label for="submit"></label>
                    <input name="submit" type="submit" class="form-control btn btn-primary" value="Verzenden" id="submit">
                </div>
            </form>

        </div>
        <div class="col-sm-1"></div>
    </div>
@endsection

resources/views/addItem.blade.php
@extends('layouts.app')

@section('content')
<div class="row h-100">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
        <h1>Backlogitem toevoegen</h1>
        <form action={{route('project.item.store', ['project' => $project->id])}} method="post">
            @csrf
            <div class="form-group">
                <label>Naam:</label>
                <input name="name" type="text" class="form-control" id="name">
            </div>

            <div class="form-group">
                <label>Beschijving:</label>
                <textarea name="description" type="text" class="form-control" id="description" rows="5" ></textarea>
            </div>

            <div class="form-group">
                <label>asingnee:</label>
                <select class="form-control" id="user" name="user">
                    @foreach($users as $user)
                        <option value={{$user->id}}>{{$user->username}}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label>Type item:</label>
                <select class="form-control" id="type" name="type">
                    @foreach($types as $type)
                        <option value={{$type->id}}>{{$type->type}}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label>sprint:</label>
                <select class="form-control" id="sprint_id" name="sprint_id">
                    @foreach($sprints as $sprint)
                        <option value={{$sprint->id}}>{{$sprint->name}}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label>Punten:</label>
                <input name="story_points" type="number" class="form-control" id="story_points">
            </div>

            <div class="form-group">
                <label>Business value:</label>
                <input name="business_value" type="number" class="form-control" id="business_value">
            </div>

            <div class="btn-group">
                <label for="submit"></label>
                <input name="submit" type="submit" class="form-control btn btn-primary" value="Verzenden" id="submit">
            </div>
        </form>

    </div>
    <div class="col-sm-1"></div>
</div>
@endsection

resources/views/backlog.blade.php
@extends ('layouts.app')

@section ('toast')
    <body>
    @foreach ($backlogs as $backlog)
    <div class="container">
        <div class="toast" data-autohide="false">
            <div class="toast-header">
                <strong class="mr-auto text-primary"><a href="/backlog/{{ $backlog->id }}">{{ $backlog->title }}</a></strong>
                <small class="text-muted">5 mins ago</small>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast">&times;</button>
            </div>
            <div class="toast-body">
                {{ $backlog->body }}
            </div>
        </div>
    </div>
    @endforeach
    <script>
        $(document).ready(function(){
            $('.toast').toast('show');
        });
    </script>
    <div class="container">
        <div class="toast" data-autohide="false" style="padding: 3%">
            <button onclick="hideshow()" class="btn btn-primary" id="show_button" style="margin-bottom: 5%">Add</button>
            <form method="post" action="/backlogs" id="formElement" style="display: none">
                @csrf

                <div class="form-group">
                    <label class="label" for="title">
                    <input type="title" class="form-control" id="title" placeholder="Title">
                </div>
                <div class="form-group">
                    <label class="label" for="body">
                    <input type="body" class="form-control" id="body" placeholder="Text">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
            </form>
        </div>
    </div>
    <script type="text/javascript">
        var button = document.getElementById('show_button')
        button.addEventListener('click',hideshow,false);

        function hideshow() {
            document.getElementById('formElement').style.display = 'block';
            this.style.display = 'none'
        }
    </script>
@endsection

resources/views/childItemShow.blade.php
@extends('layouts.app')

@section('content')
    <div class="row h-100">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <h1>Backlogitems</h1>
            @foreach($childBacklogItems as $childBacklogItem)
                <div class="row">
                    <div class="col-sm-1"></div>
                    <div class="col-sm-10">
                        <div class="text-center">
                            <h1>{{$childBacklogItem->title}}</h1>
                        </div>
                        <div>
                            <p>{{$childBacklogItem->description}}
                            <p>storypoints = {{$childBacklogItem->story_points}}</p>
                            <p>Buisness Value = {{$childBacklogItem->business_value}}</p>
                        </div>
                    </div>
                    <div class="col-sm-1"></div>
                </div>
            @endforeach
        </div>
        <div class="col-sm-1"></div>
    </div>
@endsection

resources/views/definitionOfDone.blade.php
@extends('layouts.app')

@section('content')
    @include('components.model')

    <body style="height: 100%">
    <div class="text-center"><h1 class="p-3">Defenition Of Done</h1></div>
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-7"></div>
        <div class="col-sm-2">
            <form>
                <button type="button" class="btn btn-primary m-2" data-toggle="modal" data-target="#myModal">voeg toe
                </button>
                <input type="hidden" value="{{request()->route('dod')}}">
            </form>
        </div>
        <div class="col-sm-1"></div>
    </div>
    @foreach($dodItems as $doDItem)
        <div class="row h-100">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <div class="container border-left border-right border-top rounded p5">
                    <div class="card m-3">
                        <div class="card-body">
                            <p class="card-text">{{$doDItem['text']}}</p>
                            <div class="btn-group float-right">
                                <form method="get" action="/edit_dod_item/{{$doDItem->id}}">
                                    @csrf
                                    <button type="submit" class="btn btn-primary">pas aan</button>
                                </form>
                                <form method="post" action="/delete_dod_item/{{$doDItem->id}}">
                                    @csrf
                                    {{method_field('DELETE')}}
                                    <button type="submit" class="btn btn-danger">verwijder</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2"></div>
            </div>
        </div>
    @endforeach
    </body>
@endsection

resources/views/definitionOfDoneEdit.blade.php
@extends('layouts.app')

@section('content')
    <div class="modal-body">
        <form action="/update/dod_item/{{$definitionOfDoneItem->id}}" method="post">
            @csrf
            {{method_field('PUT')}}
            <input type="text" name="text">
            <button class="btn btn-primary" type="submit" name="submit">submit</button>
        </form>
    </div>
@endsection

resources/views/deleteChildItemForm.blade.php
@extends('layouts.app')

@section('content')
    <div class="row h-100">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <h1>Child-Item Verwijderen</h1><hr>
            <div class="row h-100">
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-3">
                            item ID
                        </div>
                        <div class="col-sm-4">
                            item Naam
                        </div>
                    </div><hr>
                    @foreach($childItems as $item)
                        <div class="col-sm-12"><br>
                            <form method="post" action=/delete_child_item/delete/{{$item['id']}} >
                                @csrf
                                <div class="row">
                                    <div class="col-sm-3">
                                        {{$item['id']}}
                                    </div>
                                    <div class="col-sm-4">
                                        {{$item['title']}}
                                    </div>
                                    <div class="btn-group">
                                        <label for="submit"></label>
                                        <input name="submit" type="submit" class="form-control btn btn-primary" value="Verzenden" id="submit">
                                    </div>
                                </div>
                            </form>
                        </div>

                    @endforeach
                    <br>
                    <a href="home" class="btn btn-primary float-left" role="button">Terug</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-1"></div>
    </div>
@endsection

resources/views/deleteItemForm.blade.php
@extends('layouts.app')

@section('content')
    <div class="row h-100">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <h1>Backlog-item Verwijderen</h1><hr>
            <div class="row h-100">
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-3">
                            item ID
                        </div>
                        <div class="col-sm-4">
                           item Naam
                        </div>
                    </div><hr>
                    @foreach($backlogItems as $item)
                        <div class="col-sm-12"><br>
                            <form method="post" action=/deleteItem/delete/{{$item['id']}} >
                                @csrf
                            <div class="row">
                                <div class="col-sm-3">
                                    {{$item['id']}}
                                </div>
                                <div class="col-sm-4">
                                    {{$item['title']}}
                                </div>
                                <div class="btn-group">
                                    <label for="submit"></label>
                                    <input name="submit" type="submit" class="form-control btn btn-primary" value="Verzenden" id="submit">
                                </div>
                            </div>
                            </form>
                            </div>

                                @endforeach
                            <br>
                            <a href="home" class="btn btn-primary float-left" role="button">Terug</a>
                        </div>
                </div>
            </div>
        </div>
        <div class="col-sm-1"></div>
    </div>
@endsection

resources/views/messages.blade.php
@if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('error'))
    <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('warning'))
    <div class="alert alert-warning alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('info'))
    <div class="alert alert-info alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($errors->any())
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        Whoops, something went wrong... Please check the form below for errors
    </div>
@endif

resources/views/productBacklog.blade.php
@extends('layouts.app')

@section('content')
<body style="height: 100%">
<div class="text-center"><h1 class="p-3">Product Backlog items</h1></div>

  <div class="row h-100">
        <div class="col-sm-2"></div>
      <div class="col-sm-8">
          <div class="container border-left border-right border-top rounded p5">
              <div class="card m-3">
                  <div class="card-body">
                      <div class="row">
                        <h5 class="card-title col-sm-6">Title</h5>
                        <h6 class="text-right col-sm-4">NAME</h6>
                          <h6 class="text-right col-sm-2">points:66</h6>
                      </div>
                      <p class="card-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus</p>
                  </div>
              </div>

              <div class="card m-3">
                  <div class="card-body">
                      <div class="row">
                          <h5 class="card-title col-sm-6">Title</h5>
                          <h6 class="text-right col-sm-4">NAME</h6>
                          <h6 class="text-right col-sm-2">points:66</h6>
                      </div>
                      <p class="card-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus</p>
                  </div>
              </div>
                <div class="col-sm-2"></div>
          </div>
      </div>
  </div>
</body>
@endsection

resources/views/sprintEdit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
        <form class="float-left position-fixed" action="{{ route('project.show', ['project' => $project->id]) }}">
            <button class="btn">
                <i class="fas fa-angle-left"></i> Back
            </button>
        </form>
        <h2 class="text-center">{{$sprint->name}}</h2><hr>
    </div>
    <div class="col-sm-3"></div>
</div>
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <form method='post' action='{{route('project.sprint.update', ['project' => $project->id, 'sprint' => $sprint->id])}}' enctype="multipart/form-data">
                    @csrf
                    @method('PUT')

                    <div class="form-group1">
                        <label for="name"><h10>Sprint Naam:</h10></label>
                        <input type="text" class="form-control" name="name" id="name" required="required"
                               value="{{ $sprint->name }}"/>

                    </div><br>

                    <div class="form-group1">
                        <label for="startdate"><h10>Sprint Start Datum:</h10></label>
                        <input type="text" class="form-control" name="startDate" id="start_date" required="required"
                               value="{{ $sprint->start_date }}"/>
                    </div><br>

                    <div class="form-group1">
                        <label for="enddate"><h10>Sprint Finish Datum:</h10></label>
                        <input type="text" class="form-control" name="endDate" id="end_date" required="required"
                               value="{{ $sprint->end_date }}"/>
                    </div><br>

                    <button type="submit" class="btn btn-primary float-right">Update</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-sm-3"></div>
</div>
@endsection

resources/views/teamEdit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row h-100">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <h1>Update</h1>
            <hr>
            <div class="row h-100">
                <div class="col-sm-5">
                    <form method='post' action='{{route('team.update', ['team' => $team->id])}}' enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <div id="container">
                            <div class="form-group1">
                                <label for="name">Team Naam:</label>
                                <input type="text" class="form-control" name="name" id="name" required="required"
                                       value="{{ $team->name }}"/>
                            </div>
                            <br>
                            <div class="form-group1">
                                <label for="description">Team Omschrijving:</label>
                                <input type="text" class="form-control" name="description" id="description"
                                       value="{{ $team->description }}" required="required"/>
                            </div>
                            <br>
                            <div class="form-group1 field" id="content">
                                <div class="select is-multiple control mt-3">
                                    <select
                                        name="users[]"
                                        multiple
                                    >
                                        @foreach($users as $user)
                                            <option value="{{ $user->id }}">{{ $user->username }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-primary float-right">Update</button>
                    </form>
                </div>
                <div class="col-sm-1"></div>
                <div class="col-sm-5">
                    <div class="row">
                        <table>
                            <tr>
                                <th>Teamleden</th>
                                <th></th>
                            </tr>
                            @foreach($team->users as $user)
                                <tr>
                                    <form method='post' action='{{route('team.deleteUser', ['team' => $team->id, 'user' => $user->id])}}'>
                                        @csrf
                                        {{method_field('DELETE')}}
                                        <td>
                                            <button type="submit" class="btn-btn btn-primary float-left" style="">x
                                            </button>
                                        </td>
                                        <td>
                                            <a href="#">{{ $user->username }}</a>
                                        </td>
                                    </form>
                                    <form method='post' action='{{route('team.updateRole', ['team' => $team->id, 'user' => $user->id])}}'>
                                        @csrf
                                        @method('PUT')
                                        <td>
                                            <select name="role_id" size="1">
                                                @foreach ($roles as $role)
                                                    <option value="{{ $role->id }}"{{ $role->id == $user->pivot->role_id ? " selected" : "" }}>{{ $role->role }}</option>
                                                @endforeach
                                            </select>
                                        </td>
                                        <td>
                                            <button type="submit" class="btn-btn btn-primary float-left" style="">+
                                            </button>
                                        </td>
                                    </form>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-sm-1"></div>
        </div>
    </div>
@endsection

resources/views/teamOverview.blade.php
@extends('layouts.app')

@section('content')
    <div class="row h-100">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <h1>Team Overview</h1>
            <hr>
            <div class="row h-100">
                <div class="col-sm-5">
                    <h10>Maak een nieuwe team aan</h10>
                    <hr>

                </div>
                <div class="col-sm-1"></div>
                <div class="col-sm-5">
                    <h10>Verwijder een team</h10>
                    <hr>
                    <div class="row">
                        <table>
                            <tr>
                                <th class="col-4">Team Naam</th>
                                <th class="col-4">Team Omschrijving</th>
                                <th class="col-4">Edit</th>
                                <th class="col-4">Delete</th>
                            </tr>
                                @foreach($teams as $team)
                                    <tr>
                                        <td>{{ $team->name }}</td>
                                        <td>{{ $team->description }}</td>
                                        <td>
                                            <form method='get' action='{{route('team.edit', ['team' => $team->id])}}' style="display: inline-block; float: right">
                                                <button type="submit" class="btn-warning">edit</button>
                                            </form>
                                        </td>
                                        <td>
                                            <form method='post' action='{{route('team.destroy', ['team' => $team->id]) }}' style="display: inline-block">
                                                @csrf
                                                {{method_field('DELETE')}}
                                                <button type="submit" class="btn-btn btn-primary float-right" style="">
                                                    verwijderen
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                        </table>
                    </div>
                </div>
            <div class="col-sm-1"></div>
        </div>
    </div>
@endsection