routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//users
Auth::routes();
Route::get('/account_overview', 'AccountController@showAccountOverview');

//home
Route::get('/', 'ProjectController@index')->name('home')->middleware('auth');
Route::get('/home', 'ProjectController@index')->name('home')->middleware('auth');

//child item
Route::get('/addchilditem', 'ChildItemController@showAddChildItemForm');
Route::post('/addchilditem', 'ChildItemController@saveItem')->name('saveItem');
Route::get('/edit_child_item/{id}', 'ChildItemController@showEditChildItemForm');
Route::post('/edit_child_item/{id}', 'ChildItemController@updateChildItem')->name('updateChildItem');
Route::get('/delete_child_item', 'ChildItemController@showDeleteChildItem');
Route::post('/delete_child_item/delete/{id}', 'ChildItemController@deleteChildItem')->name('deleteChildItem');
Route::get('/show_child_items', 'ChildItemController@showChildItems');

//Project
Route::resource('project', 'ProjectController')->middleware('auth');
Route::post('/project/{project}/add_teams','ProjectController@addTeams')->name('project.addTeam')->middleware('auth');
Route::delete('/project/{project}/delete_team/{team}','ProjectController@deleteTeam')->name('project.deleteTeam')->middleware('auth');

//Team
Route::resource('project.team', 'TeamController')->middleware('auth');
Route::delete('project/{project}/team/{team}/user/{user}', 'Teamcontroller@deleteUser')->name('team.deleteUser')->middleware('auth');
Route::put('project/{project}/team/{team}/updateRole/{user}', 'TeamController@updateRole')->name('team.updateRole')->middleware('auth');
Route::get('/teams', 'TeamController@getAllJoinedTeams')->name('teams')->middleware('auth');

//dod
Route::resource('project.dod', 'DoDController')->middleware('auth');
Route::post('project/{project}/dod/{definitionOfDone}/dod-item', 'DodController@createDodItem')->name('dod.dodItem.store')->middleware('auth');

//Sprint
Route::resource('project.sprint', 'SprintController')->middleware('auth');
Route::resource('sprints', 'SprintController')->middleware('auth');

//Item
Route::resource('project.sprint.item', 'ItemController')->middleware('auth');
Route::get('/items', 'ItemController@getAssignedItems')->name('items')->middleware('auth');

//Scrum
Route::resource('project.sprint.board', 'ScrumController')->only('index')->middleware('auth');

//Backlog
Route::resource('project.backlog', 'BacklogController')->only('index')->middleware('auth');

//ADMIN
Route::get('/admin_overview', 'AdminController@showAdminOverview');

//RetrospectiveItems
Route::resource('project.sprint.retrospectiveitem', 'RetrospectiveItemsController')->only('index')->middleware('auth');
Route::delete('retrospectiveitemsDestroy/{retrospective_items}', 'RetrospectiveItemsController@destroy')->name('destroyretrospectiveitem')->middleware('auth');
Route::post('retrospectiveitemStore/{sprint}', 'RetrospectiveItemsController@store')->name('storeretrospectiveitem')->middleware('auth');
Route::put('retrospectiveitemsUpdate/{retrospective_items}', 'RetrospectiveItemsController@update')->name('updateretrospectiveitem')->middleware('auth');

//SprintReview
Route::resource('project.sprint.sprintreview', 'SprintReviewController')->only('index')->middleware('auth');
Route::post('sprintreviewStore/{sprint}', 'SprintReviewController@store')->name('storesprintreview')->middleware('auth');
Route::delete('sprintreviewDestroy/{sprint_reviews}', 'SprintReviewController@destroy')->name('destroysprintreview')->middleware('auth');
Route::put('sprintreviewUpdate/{sprint_reviews}', 'SprintReviewController@update')->name('updatesprintreview')->middleware('auth');

app/Backlog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Backlog extends Model
{
    /**
     * @return BelongsTo
     */
    public function project()
    {
        return $this->belongsTo(Project::class);
    }

    /**
     * @return HasMany
     */
    public function items()
    {
        return $this->hasMany(Item::class);
    }
}

app/Http/Controllers/BacklogController.php
<?php

namespace App\Http\Controllers;

use App\Backlog;
use App\Project;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\View\View;

class BacklogController extends Controller
{
    /**
     * @param Project $project
     *
     * @return Factory|View
     */
    public function index(Project $project)
    {
        $backlogItems = $project->backlog->items()->get();

        return view('backlogs.index', compact( 'backlogItems', 'project'));
    }
}

resources/views/backlogs/create.blade.php
@extends ('layout')

@section ('toast')
    <head>
        <title>Bootstrap Example</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    </head>
    <body>
    <div class="container">
        <div class="toast" data-autohide="false" style="padding: 3%">
            <button onclick="hideshow()" class="btn btn-primary" id="show_button" style="margin-bottom: 5%">Add</button>
            <form method="post" action="/backlog" id="formElement" style="display: none">
                @csrf
                <div class="form-group">
                    <label class="label" for="title"></label>
                    <div class="control">
                        <input type="title" class="input" id="title" placeholder="Title">
                    </div>
                </div>
                <div class="form-group">
                    <label class="label" for="body"></label>
                    <div class="control">
                        <input type="body" class="input" id="body" placeholder="Text">
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
            </form>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.toast').toast('show');
        });
        var button = document.getElementById('show_button')
        button.addEventListener('click',hideshow,false);

        function hideshow() {
            document.getElementById('formElement').style.display = 'block';
            this.style.display = 'none'
        }
    </script>
@endsection

resources/views/backlogs/index.blade.php
@extends ('layouts.app')

@section ('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-10">
                    <form class="float-left" action="{{ route('project.show', ['project' => $project->id]) }}">
                        <button class="btn">
                            <i class="fas fa-angle-left"></i> @lang('buttons.back')
                        </button>
                    </form>
                    <h1 class="text-center">Backlog</h1>
                </div>
                <div class="col-sm-1"></div>
            </div>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-2">@lang('texts.project.showProject.name')</div>
                        <div class="col-sm-4">sprint</div>
                        <div class="col-sm-2">Created at</div>
                        <div class="col-sm-2">updated at</div>
                        <div class="col-sm-2"></div>
                    </div>
                    <hr>
                    @foreach ($backlogItems as $backlogItem)
                        <div class="row p-1">
                            <div class="col-sm-2">
                                {{$backlogItem->title}}
                            </div>
                            <div class="col-sm-4">
                                {{$backlogItem->sprint->name}}
                            </div>
                            <div class="col-sm-2">
                                {{date('d F Y', strtotime($backlogItem->created_at))}}
                            </div>
                            <div class="col-sm-2">
                                {{date('d F Y', strtotime($backlogItem->updated_at))}}
                            </div>
                            <div class="col-sm-2">
                                <div class="btn-group float-right">
                                    <a data-toggle="modal" data-target="#deleteItem-{{$backlogItem->id}}" class="btn btn-danger w-auto text-light float-right" role="button">
                                        <i class="fas fa-trash-alt"></i> @lang('buttons.delete')
                                    </a>
                                    <a href="{{route('project.sprint.item.edit', ['project' => $project->id, 'sprint' => $backlogItem->sprint->id, 'item' => $backlogItem->id, 'page' => 9])}}" class="btn btn-info w-auto float-right" role="button">
                                        <i class="fas fa-edit"></i> @lang('buttons.edit')
                                    </a>
                                </div>
                                @include('components.modalDeleteItem')
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
        <div class="col-sm-1"></div>
    </div>
@endsection