routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//users
Auth::routes();
Route::get('/account_overview', 'AccountController@showAccountOverview');

//home
Route::get('/', 'ProjectController@index')->name('home')->middleware('auth');
Route::get('/home', 'ProjectController@index')->name('home')->middleware('auth');

//child item
Route::get('/addchilditem', 'ChildItemController@showAddChildItemForm');
Route::post('/addchilditem', 'ChildItemController@saveItem')->name('saveItem');
Route::get('/edit_child_item/{id}', 'ChildItemController@showEditChildItemForm');
Route::post('/edit_child_item/{id}', 'ChildItemController@updateChildItem')->name('updateChildItem');
Route::get('/delete_child_item', 'ChildItemController@showDeleteChildItem');
Route::post('/delete_child_item/delete/{id}', 'ChildItemController@deleteChildItem')->name('deleteChildItem');
Route::get('/show_child_items', 'ChildItemController@showChildItems');

//Project
Route::resource('project', 'ProjectController')->middleware('auth');
Route::post('/project/{project}/add_teams','ProjectController@addTeams')->name('project.addTeam')->middleware('auth');
Route::delete('/project/{project}/delete_team/{team}','ProjectController@deleteTeam')->name('project.deleteTeam')->middleware('auth');

//Team
Route::resource('project.team', 'TeamController')->middleware('auth');
Route::delete('project/{project}/team/{team}/user/{user}', 'Teamcontroller@deleteUser')->name('team.deleteUser')->middleware('auth');
Route::put('project/{project}/team/{team}/updateRole/{user}', 'TeamController@updateRole')->name('team.updateRole')->middleware('auth');
Route::get('/teams', 'TeamController@getAllJoinedTeams')->name('teams')->middleware('auth');

//dod
Route::resource('project.dod', 'DoDController')->middleware('auth');
Route::post('project/{project}/dod/{definitionOfDone}/dod-item', 'DodController@createDodItem')->name('dod.dodItem.store')->middleware('auth');

//Sprint
Route::resource('project.sprint', 'SprintController')->middleware('auth');
Route::resource('sprints', 'SprintController')->middleware('auth');

//Item
Route::resource('project.sprint.item', 'ItemController')->middleware('auth');
Route::get('/items', 'ItemController@getAssignedItems')->name('items')->middleware('auth');

//Scrum
Route::resource('project.sprint.board', 'ScrumController')->only('index')->middleware('auth');

//Backlog
Route::resource('project.backlog', 'BacklogController')->only('index')->middleware('auth');

//ADMIN
Route::get('/admin_overview', 'AdminController@showAdminOverview');

//RetrospectiveItems
Route::resource('project.sprint.retrospectiveitem', 'RetrospectiveItemsController')->only('index')->middleware('auth');
Route::delete('retrospectiveitemsDestroy/{retrospective_items}', 'RetrospectiveItemsController@destroy')->name('destroyretrospectiveitem')->middleware('auth');
Route::post('retrospectiveitemStore/{sprint}', 'RetrospectiveItemsController@store')->name('storeretrospectiveitem')->middleware('auth');
Route::put('retrospectiveitemsUpdate/{retrospective_items}', 'RetrospectiveItemsController@update')->name('updateretrospectiveitem')->middleware('auth');

//SprintReview
Route::resource('project.sprint.sprintreview', 'SprintReviewController')->only('index')->middleware('auth');
Route::post('sprintreviewStore/{sprint}', 'SprintReviewController@store')->name('storesprintreview')->middleware('auth');
Route::delete('sprintreviewDestroy/{sprint_reviews}', 'SprintReviewController@destroy')->name('destroysprintreview')->middleware('auth');
Route::put('sprintreviewUpdate/{sprint_reviews}', 'SprintReviewController@update')->name('updatesprintreview')->middleware('auth');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Item extends Model
{

    /**
     * @return BelongsTo
     */
    public function sprint()
    {
        return $this->belongsTo(Sprint::class);
    }

    /**
     * @return BelongsTo
     */
    public function backlog()
    {
        return $this->belongsTo(Backlog::class);
    }

    /**
     * @return BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return BelongsTo
     */
    public function type()
    {
        return $this->belongsTo(Type::class);
    }

    /**
     * @return HasMany
     */
    public function childItems()
    {
        return $this->hasMany(ChildItem::class);
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateItemRequest;
use App\Http\Requests\UpdateItemRequest;
use App\Item;
use App\Project;
use App\Sprint;
use App\Type;
use App\User;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class ItemController extends Controller
{
    public function index()
    {

    }

    /**
     * @param Project $project
     * @param Sprint $sprint
     * @param CreateItemRequest $request
     *
     * @return RedirectResponse
     */
    public function store(Project $project, Sprint $sprint, CreateItemRequest $request)
    {
        $item = new Item();
        $item->title = $request->get('name');
        $item->description = $request->get('description');
        $item->user_id = $request->get('user');
        $item->story_points = $request->get('story_points');
        $item->business_value = $request->get('business_value');
        $item->type_id = $request->get('type');
        $item->sprint_id = $sprint->id;
        $item->backlog_id = $project->backlog()->first()->id;

        $item->save();

        return redirect()->back()->with('success','Item created successfully!');;
    }

    /**
     * @param Project $project
     * @param Sprint $sprint
     *
     * @return Factory|View
     */
    public function create(Project $project, Sprint $sprint)
    {
        $users = User::all();
        $types = Type::all();
        $sprints = Sprint::all();

        return view('addItem',
            compact('types', 'users', 'sprints', 'project'));
    }

    /**
     * @param Project $project
     * @param Sprint $sprint
     * @param Item $item
     * @param UpdateItemRequest $request
     *
     * @param $pageValue
     * @return RedirectResponse
     */
    public function update(Project $project, Sprint $sprint, Item $item, UpdateItemRequest $request)
    {
        $item->title = $request->get('title');
        $item->description = $request->get('description');
        $item->user_id = $request->get('user_id');
        $item->story_points = $request->get('story_points');
        $item->business_value = $request->get('business_value');
        $item->type_id = $request->get('type_id');
        $item->sprint_id = $request->get('sprint_id');
        $item->backlog_id = $project->backlog()->first()->id;

        $item->save();
        if ($request->get('page') == 9) {
            return redirect()->route('project.backlog.index', [
                'project' => $project->id,
            ])->with('info', 'Item updatet successfully!');
        }

        return redirect()->route('project.sprint.board.index', [
            'project' => $project->id,
            'sprint' => $sprint->id,
        ])->with('info','Item updatet successfully!');
    }

    public function show(Project $project, Sprint $sprint, Item $item)
    {
        return view('itemShow',
            compact('project', 'sprint', 'item'));
    }

    /**
     * @param $id
     *
     * @return RedirectResponse
     */
    public function destroy($id)
    {
        $item = Item::find($id);
        $item->delete();

        return redirect()->back()->with('warning','Item deleted successfully!');;
    }

    /**
     * @param Project $project
     * @param Sprint $sprint
     * @param Item $item
     *
     * @return Factory|View
     */
    public function edit(Project $project, Sprint $sprint, Item $item)
    {
        $users = User::where('id', $item->user_id)->first();
        $allUsers = User::all();
        $types = Type::all();
        $sprints = Sprint::all();

        return view('editItem',
            compact('types', 'users', 'project', 'sprints', 'allUsers', 'item', 'sprint'));
    }

    /**
     * @return Factory|View
     */
    public function getAssignedItems()
    {
        $user = Auth::user();
        $items = $user->items()->get();

        return view('items.assignedItems',
            compact('items', 'user'));
    }
}

resources/views/items/assignedItems.blade.php
@extends ('layouts.app')

@section ('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-10">
                    <h1 class="text-center">Assigned items</h1>
                </div>
                <div class="col-sm-1"></div>
            </div>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-2">@lang('texts.project.showProject.name')</div>
                        <div class="col-sm-4">sprint</div>
                        <div class="col-sm-2">Created at</div>
                        <div class="col-sm-2">updated at</div>
                        <div class="col-sm-2"></div>
                    </div>
                    <hr>
                    @foreach ($items as $item)
                        <div class="row p-1">
                            <div class="col-sm-2">
                                {{$item->title}}
                            </div>
                            <div class="col-sm-4">
                                {{$item->sprint->name}}
                            </div>
                            <div class="col-sm-2">
                                {{date('d F Y', strtotime($item->created_at))}}
                            </div>
                            <div class="col-sm-2">
                                {{date('d F Y', strtotime($item->updated_at))}}
                            </div>
                            <div class="col-sm-2">
                                <div class="btn-group float-right">
                                    <a href="{{route('project.sprint.item.show', ['project' => $item->sprint->project->id, 'sprint' => $item->sprint->id, 'item' => $item->id])}}"
                                       class="btn btn-primary w-auto float-right" role="button">
                                        <i class="fas fa-eye"></i> @lang('buttons.show')
                                    </a>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
        <div class="col-sm-1"></div>
    </div>
@endsection